### ISSUE TITLE
`login_url` does not exist

### ISSUE THREAD

**Issue by buschtoens** [verdaccio/flow-types#69]
#19 & #20 have added the `login_url` field to `IPluginAuth`. Unfortunately though https://github.com/verdaccio/verdaccio/pull/834 was never merged.

Either we need to remove `login_url` from the types or work on getting https://github.com/verdaccio/verdaccio/pull/834 in, which I'd love to have, since I am working on [`verdaccio-oidc`](https://github.com/ClarkSource/verdaccio-oidc). 😄

**Comment by juanpicado** [comment]
hi @buschtoens . I cannot see you repo 🙃 . Somehow, a long of time has passed since https://github.com/verdaccio/verdaccio/pull/834 and now the UI remains n another repo.

Anyway, could you describe more or less how the plugin looks like and the whole flow in general?

**Comment by buschtoens** [comment]
Whoops, sorry! The repo is now public. 😄 

`verdaccio-oidc` will implement a Single Sign On OpenID Connect [`response_type=code` authorization flow](https://medium.com/@darutk/diagrams-of-all-the-openid-connect-flows-6968e3990660#c027) for authenticating against an OpenID provider.

For the npm client the authentication works like this:

```bash
npm login --auth-type=sso --registry=https://example.com
```

But for the web UI, I would like the button to not trigger the login form modal, but instead redirect to a URL that is provided by my plugin, e.g. `/-/oidc/authorize`.

[`verdaccio-github-oauth-ui`](https://github.com/n4bb12/verdaccio-github-oauth-ui) works around this by ["hacking" into the UI](https://github.com/n4bb12/verdaccio-github-oauth-ui/blob/master/src/client/login-button.ts), but this is needlessly complicated.
